language: java
sudo: true
dist: trusty
jdk: oraclejdk11
addons:
  apt:
    packages:
      - oracle-java11-installer
before_install:
  - chmod +x mvnw
deploy:
  provider: heroku
  api-key: $HEROKU_API_KEY
  app: reactive-algomessiahs
  on:
    all_branches: true
